# A mock database of available products
fake_products_db = [
    {"item_name": "Customer Support Auto-Responder", "sku": "CS-001", "price": 499.00, "stock": 500, "image_url": "https://api.dicebear.com/9.x/bottts/svg?seed=CS-001&backgroundColor=b6e3f4"},
    {"item_name": "Sales Lead Qualification Bot", "sku": "SL-001", "price": 899.00, "stock": 300, "image_url": "https://api.dicebear.com/9.x/bottts/svg?seed=SL-001&backgroundColor=c0aede"},
    {"item_name": "Automated Data Entry Assistant", "sku": "DE-001", "price": 299.00, "stock": 1000, "image_url": "https://api.dicebear.com/9.x/bottts/svg?seed=DE-001&backgroundColor=ffdfbf"},
    {"item_name": "HR Onboarding Copilot", "sku": "HR-001", "price": 650.00, "stock": 400, "image_url": "https://api.dicebear.com/9.x/bottts/svg?seed=HR-001&backgroundColor=b6e3f4"},
    {"item_name": "Financial Report Generator", "sku": "FIN-001", "price": 1200.00, "stock": 150, "image_url": "https://api.dicebear.com/9.x/bottts/svg?seed=FIN-001&backgroundColor=c0aede"},
    {"item_name": "Inventory Forecasting AI", "sku": "INV-001", "price": 1500.00, "stock": 100, "image_url": "https://api.dicebear.com/9.x/bottts/svg?seed=INV-001&backgroundColor=ffdfbf"},
    {"item_name": "Cybersecurity Threat Analyzer", "sku": "SEC-001", "price": 2500.00, "stock": 75, "image_url": "https://api.dicebear.com/9.x/bottts/svg?seed=SEC-001&backgroundColor=b6e3f4"},
    {"item_name": "Marketing Campaign Optimizer", "sku": "MKT-001", "price": 950.00, "stock": 250, "image_url": "https://api.dicebear.com/9.x/bottts/svg?seed=MKT-001&backgroundColor=c0aede"},
    {"item_name": "Legal Document Reviewer", "sku": "LGL-001", "price": 1800.00, "stock": 120, "image_url": "https://api.dicebear.com/9.x/bottts/svg?seed=LGL-001&backgroundColor=ffdfbf"},
    {"item_name": "Social Media Sentinel", "sku": "SM-001", "price": 550.00, "stock": 600, "image_url": "https://api.dicebear.com/9.x/bottts/svg?seed=SM-001&backgroundColor=b6e3f4"},
    {"item_name": "Code Review Assistant Pro", "sku": "DEV-001", "price": 1100.00, "stock": 200, "image_url": "https://api.dicebear.com/9.x/bottts/svg?seed=DEV-001&backgroundColor=c0aede"},
    {"item_name": "Enterprise Search AI", "sku": "ES-001", "price": 2200.00, "stock": 50, "image_url": "https://api.dicebear.com/9.x/bottts/svg?seed=ES-001&backgroundColor=ffdfbf"},
    {"item_name": "Meeting Summarizer Bot", "sku": "MTG-001", "price": 350.00, "stock": 800, "image_url": "https://api.dicebear.com/9.x/bottts/svg?seed=MTG-001&backgroundColor=b6e3f4"},
    {"item_name": "Predictive Maintenance AI", "sku": "PM-001", "price": 3000.00, "stock": 30, "image_url": "https://api.dicebear.com/9.x/bottts/svg?seed=PM-001&backgroundColor=c0aede"},
    {"item_name": "Supply Chain Routing Optimizer", "sku": "SC-001", "price": 2800.00, "stock": 40, "image_url": "https://api.dicebear.com/9.x/bottts/svg?seed=SC-001&backgroundColor=ffdfbf"},
    {"item_name": "Compliance Monitoring Agent", "sku": "CMP-001", "price": 1600.00, "stock": 110, "image_url": "https://api.dicebear.com/9.x/bottts/svg?seed=CMP-001&backgroundColor=b6e3f4"},
    {"item_name": "Customer Feedback Sentiment Engine", "sku": "CF-001", "price": 750.00, "stock": 350, "image_url": "https://api.dicebear.com/9.x/bottts/svg?seed=CF-001&backgroundColor=c0aede"},
    {"item_name": "Internal Knowledge Base Bot", "sku": "KB-001", "price": 850.00, "stock": 280, "image_url": "https://api.dicebear.com/9.x/bottts/svg?seed=KB-001&backgroundColor=ffdfbf"},
    {"item_name": "Executive Dashboard AI", "sku": "EXEC-001", "price": 3500.00, "stock": 25, "image_url": "https://api.dicebear.com/9.x/bottts/svg?seed=EXEC-001&backgroundColor=b6e3f4"},
    {"item_name": "Automated Pricing Strategy AI", "sku": "PRC-001", "price": 1950.00, "stock": 90, "image_url": "https://api.dicebear.com/9.x/bottts/svg?seed=PRC-001&backgroundColor=c0aede"},
    {"item_name": "Recruitment Sourcing Agent", "sku": "REC-001", "price": 800.00, "stock": 320, "image_url": "https://api.dicebear.com/9.x/bottts/svg?seed=REC-001&backgroundColor=ffdfbf"},
    {"item_name": "Contract Lifecycle AI", "sku": "CTR-001", "price": 1450.00, "stock": 130, "image_url": "https://api.dicebear.com/9.x/bottts/svg?seed=CTR-001&backgroundColor=b6e3f4"},
    {"item_name": "RFP Response Generator", "sku": "RFP-001", "price": 1750.00, "stock": 85, "image_url": "https://api.dicebear.com/9.x/bottts/svg?seed=RFP-001&backgroundColor=c0aede"},
    {"item_name": "Video Analytics Sentinel", "sku": "VID-001", "price": 2700.00, "stock": 60, "image_url": "https://api.dicebear.com/9.x/bottts/svg?seed=VID-001&backgroundColor=ffdfbf"},
    {"item_name": "Expense Auditing Agent", "sku": "EXP-001", "price": 600.00, "stock": 450, "image_url": "https://api.dicebear.com/9.x/bottts/svg?seed=EXP-001&backgroundColor=b6e3f4"},
    {"item_name": "IT Helpdesk Resolution Bot", "sku": "IT-001", "price": 1050.00, "stock": 210, "image_url": "https://api.dicebear.com/9.x/bottts/svg?seed=IT-001&backgroundColor=c0aede"}
]
